### ISSUE TITLE
"SentryError: Invalid Dsn" when following Development steps

### ISSUE THREAD

**Issue by rlr** [mozilla/blurts-server#1135]
```
[nodemon] starting `node server.js`
/Users/rlr/dev/blurts-server/node_modules/@sentry/core/dist/dsn.js:66
            throw new error_1.SentryError('Invalid Dsn');
            ^

SentryError: Invalid Dsn
    at new SentryError (/Users/rlr/dev/blurts-server/node_modules/@sentry/core/dist/error.js:21:28)
    at Dsn.fromString (/Users/rlr/dev/blurts-server/node_modules/@sentry/core/dist/dsn.js:66:19)
    at new Dsn (/Users/rlr/dev/blurts-server/node_modules/@sentry/core/dist/dsn.js:39:18)
    at NodeClient.BaseClient (/Users/rlr/dev/blurts-server/node_modules/@sentry/core/dist/baseclient.js:113:24)
    at new NodeClient (/Users/rlr/dev/blurts-server/node_modules/@sentry/node/dist/client.js:98:23)
    at Object.initAndBind (/Users/rlr/dev/blurts-server/node_modules/@sentry/core/dist/sdk.js:20:18)
    at Object.init (/Users/rlr/dev/blurts-server/node_modules/@sentry/node/dist/sdk.js:74:12)
    at Object.<anonymous> (/Users/rlr/dev/blurts-server/server.js:6:8)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
```

I tried setting `SENTRY_DSN=` but then it complained about missing a required setting.

I guess Issue #1069 is related.

**Comment by maxxcrawford** [comment]
@rlr I was setting up a new machine today for this project and had this same issue, but it was resolved with leaving the `SENTRY_DSN` as blank.

**Comment by groovecoder** [comment]
Sent https://github.com/mozilla/blurts-server/pull/1268 for this.
