### ISSUE TITLE
A TypeError is triggered on herokuapp (but not on stage/prod) after scanning a test@domain.com email address

### ISSUE THREAD

**Issue by CiprianGeorgiu** [mozilla/blurts-server#329]
[Affected versions]:
- latest Nightly 64.0a1
- Beta 63.0b3
- RC 62.0

[Affected platforms]:
- Windows 10 x64
- macOS 10.13
- Ubuntu 16.04 x64

[Steps to reproduce]:
1. Launch Firefox.
2. Navigate to https://fx-breach-alerts.herokuapp.com/
3. Scan an email address that respects the following structure: test@domain.com
e.g. test@gmail.com, test@yahoo.com, test@test.com

[Expected result]:
- Positive or negative results are displayed on the page depending of the email scanned.

[Actual result]:
- The following error is triggered: `TypeError: [scan.hbs] dataClasses.join is not a function
    at Object.<anonymous> (/app/hbs-helpers.js:12:26)
    at Object.eval [as main] (eval at createFunctionContext (/app/node_modules/handlebars/dist/cjs/handlebars/compiler/javascript-compiler.js:254:23), <anonymous>:18:92)
    at main (/app/node_modules/handlebars/dist/cjs/handlebars/runtime.js:173:32)
    at ret (/app/node_modules/handlebars/dist/cjs/handlebars/runtime.js:176:12)
    at ret (/app/node_modules/handlebars/dist/cjs/handlebars/compiler/compiler.js:525:21)
    at Object.invokePartial (/app/node_modules/handlebars/dist/cjs/handlebars/runtime.js:273:12)
    at Object.invokePartialWrapper [as invokePartial] (/app/node_modules/handlebars/dist/cjs/handlebars/runtime.js:68:39)
    at eval (eval at createFunctionContext (/app/node_modules/handlebars/dist/cjs/handlebars/compiler/javascript-compiler.js:254:23), <anonymous>:6:28)
    at Object.prog [as fn] (/app/node_modules/handlebars/dist/cjs/handlebars/runtime.js:219:12)
    at Object.<anonymous> (/app/hbs-helpers.js:26:29)
    at eval (eval at createFunctionContext (/app/node_modules/handlebars/dist/cjs/handlebars/compiler/javascript-compiler.js:254:23), <anonymous>:6:101)
    at Object.prog [as fn] (/app/node_modules/handlebars/dist/cjs/handlebars/runtime.js:219:12)
    at Object.<anonymous> (/app/hbs-helpers.js:43:26)
    at eval (eval at createFunctionContext (/app/node_modules/handlebars/dist/cjs/handlebars/compiler/javascript-compiler.js:254:23), <anonymous>:8:82)
    at Object.prog [as fn] (/app/node_modules/handlebars/dist/cjs/handlebars/runtime.js:219:12)
    at Object.<anonymous> (/app/hbs-helpers.js:43:26)`

[Regression range]:
- It seems to be a regression since I cannot reproduce this on https://blurts-server.stage.mozaws.net/

[Additional notes]:
- please note that this issue (as stated above) does not reproduce on stage.

**Comment by CiprianGeorgiu** [comment]
Verified fixed on 62.0 (20180830143136) running Windows 10 x64, macOS 10.13 and Ubuntu 16.04 x64.
