### ISSUE TITLE
Error: Mail command failed: 421 Timeout waiting for data from client.

### ISSUE THREAD

**Issue by groovecoder** [mozilla/blurts-server#331]
Environment:
Localhost, using AWS SES in `SMTP_URL`

STR:

1. Clicked subscribe
2. Entered "lcrouch@mozilla.com"
3. Clicked "Verify your subscription" in email

Expected results:
Land on http://localhost:6060/user/verify?token=... with confirmation and a report email sent

Actual results:

```
Error: Mail command failed: 421 Timeout waiting for data from client.
    at SMTPConnection._formatError (/Users/lcrouch/code/mozilla/blurts-server/node_modules/nodemailer/lib/smtp-connection/index.js:606:19)
    at SMTPConnection._actionMAIL (/Users/lcrouch/code/mozilla/blurts-server/node_modules/nodemailer/lib/smtp-connection/index.js:1365:34)
    at SMTPConnection._responseActions.push.str (/Users/lcrouch/code/mozilla/blurts-server/node_modules/nodemailer/lib/smtp-connection/index.js:855:18)
    at SMTPConnection._processResponse (/Users/lcrouch/code/mozilla/blurts-server/node_modules/nodemailer/lib/smtp-connection/index.js:762:20)
    at SMTPConnection._onData (/Users/lcrouch/code/mozilla/blurts-server/node_modules/nodemailer/lib/smtp-connection/index.js:558:14)
    at TLSSocket._socket.on.chunk (/Users/lcrouch/code/mozilla/blurts-server/node_modules/nodemailer/lib/smtp-connection/index.js:510:47)
    at TLSSocket.emit (events.js:159:13)
    at addChunk (_stream_readable.js:265:12)
    at readableAddChunk (_stream_readable.js:252:11)
    at TLSSocket.Readable.push (_stream_readable.js:209:10)
    at TLSWrap.onread (net.js:608:20)
```

**Comment by groovecoder** [comment]
Note: this went away, but indicates that we need better error-handling on `EmailUtils.sendMail`

**Comment by tcinotto** [comment]
Fixing actual issue is not blocking. 
Need to have a better error page/error handling, pending investigation. Could just be staging. 
Need navigation from error pages, would need some visual or design for an error page. Header and footer the same then something went wrong, try again.

**Comment by groovecoder** [comment]
Adding `needs:UX` for some visual/interaction treatment for the/a generic error page ...

![screen shot 2018-09-06 at 3 08 08 pm](https://user-images.githubusercontent.com/71928/45183432-a6477f80-b1e9-11e8-8416-2b9202119c76.png)

**Comment by pdehaan** [comment]
@groovecoder I cant see from your super-handy screenshot above (thanks!), but is there a footer on that page?

Also, not sure if we want to add something else in the sidebar or some generic tips on the page to make it feel less like a dead end.

I'm not sure how we'd test all the error page possibilities to see if the `${error.message}` actually displays something user-friendly and not too developer-centric (like the screenshot above).

**Comment by groovecoder** [comment]
Yeah this will need some follow-up for the page, just wanted to get something there that wasn't the white-page stacktrace.
