### ISSUE TITLE
Debug Travis IOError: [Errno 11] Resource temporarily unavailable

### ISSUE THREAD

**Issue by groovecoder** [mozilla/blurts-server#739]
E.g., from https://travis-ci.org/mozilla/blurts-server/jobs/488575995 ...

```
  Traceback (most recent call last):
  File "/usr/local/bin/compare-locales", line 11, in <module>
    sys.exit(CompareLocales.call())
  File "/usr/local/lib/python2.7/dist-packages/compare_locales/commands.py", line 85, in call
    return cmd.handle(**vars(args))
  File "/usr/local/lib/python2.7/dist-packages/compare_locales/commands.py", line 152, in handle
    print(details)
IOError: [Errno 11] Resource temporarily unavailable
The command "compare-locales l10n.toml . `ls locales`" failed and exited with 1 during .
```

Hint: https://github.com/travis-ci/travis-ci/issues/8934

May be able to just change Travis dist from trusty to xenial?

**Comment by groovecoder** [comment]
For future reference, this turned out to be the issue:

https://github.com/travis-ci/travis-ci/issues/4704#issuecomment-348435959

[I fixed it be separating our python + node steps into separate jobs with a build matrix](https://github.com/mozilla/blurts-server/pull/740).
