### ISSUE TITLE
getPasswordTips: TypeError: Cannot read property 'root' of undefined

### ISSUE THREAD

**Issue by groovecoder** [mozilla/blurts-server#899]
Note: may be caused by a "+" sign in the email address?

STR:

1. Signed into Monitor with FxA
2. Added a secondary email address
3. Used "lcrouch+secondary@mozilla.com"
4. Clicked "Verify My Email" link in the verification email
5. Received `Cannot read property 'root' of undefined` error on the page (and the below error in the console logs)

```
ERROR: error {"stack":"TypeError: Cannot read property 'root' of undefined\n    at Object.getPasswordTips (/Users/lcrouch/code/mozilla/blurts-server/template-helpers/emails.js:114:29)\n    at Object.eval [as main] (eval at createFunctionContext (/Users/lcrouch/code/mozilla/blurts-server/node_modules/handlebars/dist/cjs/handlebars/compiler/javascript-compiler.js:257:23), <anonymous>:5:135)\n    at main (/Users/lcrouch/code/mozilla/blurts-server/node_modules/handlebars/dist/cjs/handlebars/runtime.js:175:32)\n    at ret (/Users/lcrouch/code/mozilla/blurts-server/node_modules/handlebars/dist/cjs/handlebars/runtime.js:178:12)\n    at ret (/Users/lcrouch/code/mozilla/blurts-server/node_modules/handlebars/dist/cjs/handlebars/compiler/compiler.js:526:21)\n    at Object.invokePartial (/Users/lcrouch/code/mozilla/blurts-server/node_modules/handlebars/dist/cjs/handlebars/runtime.js:283:12)\n    at Object.invokePartialWrapper [as invokePartial] (/Users/lcrouch/code/mozilla/blurts-server/node_modules/handlebars/dist/cjs/handlebars/runtime.js:68:39)\n    at eval (eval at createFunctionContext (/Users/lcrouch/code/mozilla/blurts-server/node_modules/handlebars/dist/cjs/handlebars/compiler/javascript-compiler.js:257:23), <anonymous>:5:31)\n    at Object.prog [as inverse] (/Users/lcrouch/code/mozilla/blurts-server/node_modules/handlebars/dist/cjs/handlebars/runtime.js:221:12)\n    at Object.ifCompare (/Users/lcrouch/code/mozilla/blurts-server/template-helpers/hbs-helpers.js:152:20)\n    at eval (eval at createFunctionContext (/Users/lcrouch/code/mozilla/blurts-server/node_modules/handlebars/dist/cjs/handlebars/compiler/javascript-compiler.js:257:23), <anonymous>:5:98)\n    at Object.prog [as inverse] (/Users/lcrouch/code/mozilla/blurts-server/node_modules/handlebars/dist/cjs/handlebars/runtime.js:221:12)\n    at Object.<anonymous> (/Users/lcrouch/code/mozilla/blurts-server/node_modules/handlebars/dist/cjs/handlebars/helpers/if.js:17:22)\n    at Object.eval [as main] (eval at createFunctionContext (/Users/lcrouch/code/mozilla/blurts-server/node_modules/handlebars/dist/cjs/handlebars/compiler/javascript-compiler.js:257:23), <anonymous>:10:32)\n    at main (/Users/lcrouch/code/mozilla/blurts-server/node_modules/handlebars/dist/cjs/handlebars/runtime.js:175:32)\n    at ret (/Users/lcrouch/code/mozilla/blurts-server/node_modules/handlebars/dist/cjs/handlebars/runtime.js:178:12)"}
```

**Comment by groovecoder** [comment]
Note: refreshing the page fixed it?

**Comment by lesleyjanenorton** [comment]
Closing since we've fixed this.
